-- COMANDOS 'DDL' --> Language Definition Data
-- USO DO SCHEMA -> 'GERAL'

-- CRIAR A TABELA DE 'LOJA'
CREATE TABLE IF NOT EXISTS geral.loja(
 id_loja serial PRIMARY KEY,
 cidade varchar(50) NOT NULL,
 estado varchar(30) NOT NULL,	
 ativo BOOLEAN NOT NULL DEFAULT TRUE,
 data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

-- CRIAR A TABELA DE 'PRODUTO'
CREATE TABLE IF NOT EXISTS geral.produto(
 id_produto serial PRIMARY KEY,
 nome varchar(50) NOT NULL,
 categoria varchar(20) NOT NULL,
 segmento varchar(20) NOT NULL,
 marca varchar(30) NOT NULL,	
 ativo BOOLEAN NOT NULL DEFAULT TRUE,
 data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

-- CRIAR A TABELA DE 'VENDEDOR'
CREATE TABLE IF NOT EXISTS geral.vendedor(
 id_vendedor serial PRIMARY KEY,
 nome varchar(80) NOT NULL,
 sobrenome varchar(30) NOT NULL,
 ativo BOOLEAN NOT NULL DEFAULT TRUE,
 data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

SELECT * FROM geral.loja

-- RENOMEAR UMA COLUNA DA TABELA 'LOJA'
ALTER TABLE geral.loja
RENAME COLUMN cidade TO CIDADE;

ALTER TABLE geral.loja
ALTER COLUMN id_loja type VARCHAR(20);

-- REMOVER A RESTRIÇÃO DE 'NOT NULL' NA COLUNA 'CIDADE' DA TABELA 'LOJA'
ALTER TABLE geral.loja
ALTER COLUMN cidade DROP NOT NULL;

-- REMOVER A RESTRIÇÃO DE 'NOT NULL' NA COLUNA 'ESTADO' DA TABELA 'LOJA'
ALTER TABLE geral.loja
ALTER COLUMN estado DROP NOT NULL;



-- REMOVER COLUNA ESPECÍFICA DE UMA TABELA
ALTER TABLE geral.vendedor
DROP COLUMN IF EXISTS data_criacao;

-- ALTERANDO A COLUNA 'ID_VENDEDOR' PARA O TIPO/TYPE 'VARCHAR OU CHARACTER VARYING'
ALTER TABLE geral.vendedor
ALTER COLUMN id_vendedor type VARCHAR(20);





